### ISSUE TITLE
Autopilot gke of datadog/datadog failed to create resource due to request denied

### ISSUE THREAD

**Issue by taiyyu** [DataDog/helm-charts#182]
**Describe what happened:**
Issued this command:
helm upgrade --install datadog-agent --set datadog.apiKey=<API_KEY> --set datadog.appKey=<APP_Key> --set clusterAgent.enabled=true  --set clusterAgent.metricsProvider.enabled=true --set providers.gke.autopilot=true --set datadog.logs.enabled=true --set datadog.apm.enabled=true datadog/datadog

helm version 3.4.1

Instructions from https://www.datadoghq.com/blog/gke-autopilot-monitoring/ deployed to a brand new Autopilot mode GKE in GCP. Both install and upgrade behave the same.

Received this error:
Release "datadog-agent" does not exist. Installing it now.
Error: UPGRADE FAILED: failed to create resource: admission webhook "validation.gatekeeper.sh" denied the request: [denied by autogke-no-write-mode-hostpath] hostPath volume pointerdir in container agent is accessed in write mode; disallowed in Autopilot. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume procdir used in container init-config uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume runtimesocketdir used in container init-config uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume runtimesocketdir used in container agent uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume procdir used in container agent uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume cgroups used in container agent uses path /sys/fs/cgroup which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume logdockercontainerpath used in container agent uses path /var/lib/docker/containers which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume runtimesocketdir used in container trace-agent uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume runtimesocketdir used in container process-agent uses path /var/run/containerd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume cgroups used in container process-agent uses path /sys/fs/cgroup which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume passwd used in container process-agent uses path /etc/passwd which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-write-mode-hostpath] hostPath volume procdir used in container process-agent uses path /proc which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: ["/var/log/"]. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>
[denied by autogke-no-host-port] container trace-agent specifies a host port; disallowed in Autopilot. Requesting user: <tai.yu@vida.com> and groups: <["system:authenticated"]>

NAME         	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART            	APP VERSION
datadog-agent	default  	2       	2021-03-03 14:32:01.843944 -0800 PST	failed  	datadog-2.9.8    	7

**Describe what you expected:**
I expected datadog-agent workload and service to come up seamlessly since autopilot is supported. Standard mode gke does not have this problem.

**Steps to reproduce the issue:**
Command:
helm3 upgrade --install datadog-agent --set datadog.apiKey=<API_KEY> --set datadog.appKey=<APP_Key> --set clusterAgent.enabled=true  --set clusterAgent.metricsProvider.enabled=true --set providers.gke.autopilot=true --set datadog.logs.enabled=true --set datadog.apm.enabled=true datadog/datadog

On any unmodified autopilot mode gke

**Additional environment details (Operating System, Cloud provider, etc):**
GCP, Autopilot mode GKE, helm v3.4.1, run from Mac Big Sur 11.2.2, No values.yaml

**Comment by clamoriniere** [comment]
Hi @taiyyu 

Thank you for reporting this issue.

We are aware of this problem, and we are working with google folks to solve it. Some workload permission allow list need to be rollout on GKE to be able to deploy the Datadog agent properly.

I will keep you updated when it is done.
Thanks

**Comment by taiyyu** [comment]
@clamoriniere Thank you.

Do we have any ETA from google folks? We are in the process of deploying our new production and need to make a decision to go with Standard mode or Autopilot mode since we absolutely need Datadog agent in production.

Best,
Tai

**Comment by cohenyair** [comment]
@taiyyu our ETA is about 2 weeks from today. We will update the issue as soon as the fix is rolled out. In the meantime, feel free to contact us at support@datadoghq.com for any related questions

**Comment by artman** [comment]
Is there any known workaround to getting the agent running on an Autopilot cluster?

**Comment by cohenyair** [comment]
There is no workaround at the moment. The issue should be fixed by early next week in for GKE users in Rapid Channel clusters

**Comment by teralab** [comment]
hi

i've got the same issue please keep me inform when fix is available

regards

David

**Comment by h-parker-higgins** [comment]
Howdy @cohenyair thanks for the previous update. Any movement recently?

**Comment by lmakarov** [comment]
> The issue should be fixed by early next week for GKE users in Rapid Channel clusters

Confirming that this works in a newly created "Rapid channel" Autopilot cluster.

![image](https://user-images.githubusercontent.com/1205005/112558306-ae597180-8d8b-11eb-9554-a1990fcd647c.png)

Keep in mind:

> Rapid channel is offered on an early access basis for customers who want to test new releases before they are qualified for production use or general availability. Versions available in the Rapid Channel may be subject to unresolved issues with no known workaround and are not for use with production workloads or subject to any SLAs.

**Comment by taiyyu** [comment]
@cohenyair, @lmakarov,

Thank you for this, we will try the Rapid channel version on our staging.

Any ideas on when this will be available on Regular channel to be used for production?

I'm currently on autopilot GKE v1.18.12-gke.1210 regular channel for prod that does not have any workloads due to lack of datadog support.

**Comment by cohenyair** [comment]
Thanks all for your patience. The issue has been reported by Google here:
https://cloud.google.com/kubernetes-engine/docs/release-notes#April_19_2021

We are expecting a fix in about two weeks and will update this Github issue accordingly.

**Comment by lmakarov** [comment]
@cohenyair thanks for the update.

We switched to GKE Standard as there is very little that Datadog agent can collect from a GKE Autopilot cluster. Makes the integration very limited/useless for now.

We will reevaluate Autopilot again when its observability in Datadog gets to the level of GKE Standard.

**Comment by rcaldaspf** [comment]
> Thanks all for your patience. The issue has been reported by Google here:
> https://cloud.google.com/kubernetes-engine/docs/release-notes#April_19_2021
> 
> We are expecting a fix in about two weeks and will update this Github issue accordingly.

Any updates?

**Comment by clamoriniere** [comment]
hello @rcaldaspf @lmakarov @taiyyu and @teralab,

We finally found a remediation to the `kubelet` connectivity issue. the `datadog` chart version `2.13.1` contains the fix.

please run `helm repo update` to get the last chart version. and retry to install the chart

```shell
helm repo update
helm install <RELEASE_NAME> \
    --set datadog.apiKey=<DATADOG_API_KEY> \
    --set datadog.appKey=<DATADOG_APP_KEY> \
    --set clusterAgent.enabled=true \
    --set clusterAgent.metricsProvider.enabled=true \
    --set providers.gke.autopilot=true \
    --set datadog.logs.enabled=true \
    --set datadog.apm.enabled=true \
    --set datadog.kubeStateMetricsEnabled=false \
    --set datadog.kubeStateMetricsCore.enabled=true \
    datadog/datadog
```

Sorry again for the time it took to resolve this issue. Do not hesitate to open another issue if you discover another problem.

Thanks
Cedric

**Comment by that70schris** [comment]
Hello, I'm having this issue with chart version `2.13.1` with GKE `1.19.10-gke.1700`

**Comment by stephaneetje** [comment]
I'm reopening this issue because i still have that error:

```
admission webhook "validation.gatekeeper.sh" denied the request: [denied by autogke-no-write-mode-hostpath] hostPath volume dsdsocket in container agent is accessed in write mode; disallowed in Autopilot. Requesting user: <stephane.etjemesian@reach5.co> and groups: <["system:authenticated"]>
```

i have set the same values as the one shown in @clamoriniere 's last answer.
I'm in GKE autopilot 1.20.8, and it is using datadog's chart version 2.21.0
Do you have any idea what am i doing wrong ?

**Comment by clamoriniere** [comment]
Hello @stephaneetje 

I'm starting the investigation. But base on the error, I can already tel you that it is because we are mounting the hostvolume `dsdsocket` by default (I don't see this setting in your config), but we should not do it in an GKE autogke env. 

I will keep you posted when I confirm it and when a fix will be made.

**Comment by CharlyF** [comment]
Hi @stephaneetje  - Thanks again for your report. We just merged a fix for your problem. Can you give the latest chart a go to confirm if that helps?

**Comment by stephaneetje** [comment]
Wow that was really quick, working like a charm! Thanks a lot!

**Comment by stephaneetje** [comment]
I may have talked a bit too fast, i still have a problem, pods aren't coming up (not the same problem i guess) :

```
NAME                                         READY   STATUS    RESTARTS   AGE
pod/datadog-9j5t9                            0/3     Pending   0          12m
pod/datadog-bd6mm                            0/3     Pending   0          12m
pod/datadog-cjqql                            2/3     Running   0          8m32s
pod/datadog-cluster-agent-54c8475f76-x96hs   1/1     Running   0          12m
pod/datadog-q2mgr                            0/3     Pending   0          12m
pod/datadog-v89tm                            2/3     Running   0          12m
```

here is the `describe` of one of datadog's pods :

```
  Type     Reason     Age                     From                                   Message
  ----     ------     ----                    ----                                   -------
  Normal   Scheduled  9m32s                   gke.io/optimize-utilization-scheduler  Successfully assigned datadog/datadog-cjqql to gk3-qbel1-ciam-gke-nap-9ldyq8fa-94efd17a-7mcf
  Normal   Pulling    9m29s                   kubelet                                Pulling image "gcr.io/datadoghq/agent:7.30.0"
  Normal   Pulled     9m4s                    kubelet                                Successfully pulled image "gcr.io/datadoghq/agent:7.30.0" in 24.67430942s
  Normal   Created    8m57s                   kubelet                                Created container init-volume
  Normal   Started    8m55s                   kubelet                                Started container init-volume
  Normal   Pulled     8m54s                   kubelet                                Container image "gcr.io/datadoghq/agent:7.30.0" already present on machine
  Normal   Created    8m54s                   kubelet                                Created container init-config
  Normal   Started    8m52s                   kubelet                                Started container init-config
  Normal   Pulled     8m51s                   kubelet                                Container image "gcr.io/datadoghq/agent:7.30.0" already present on machine
  Normal   Created    8m51s                   kubelet                                Created container agent
  Normal   Started    8m44s                   kubelet                                Started container agent
  Normal   Pulled     8m44s                   kubelet                                Container image "gcr.io/datadoghq/agent:7.30.0" already present on machine
  Normal   Created    8m44s                   kubelet                                Created container trace-agent
  Normal   Started    8m36s                   kubelet                                Started container trace-agent
  Normal   Pulled     8m36s                   kubelet                                Container image "gcr.io/datadoghq/agent:7.30.0" already present on machine
  Normal   Created    8m36s                   kubelet                                Created container process-agent
  Normal   Started    8m28s                   kubelet                                Started container process-agent
  Warning  Unhealthy  7m24s (x2 over 8m24s)   kubelet                                Liveness probe failed: HTTP probe failed with statuscode: 500
  Warning  Unhealthy  4m17s (x17 over 8m17s)  kubelet                                Readiness probe failed: HTTP probe failed with statuscode: 500
```

Liveness is never going ok

**Comment by clamoriniere** [comment]
Hello @stephaneetje 

I see several issues here:
* on some node the agent can be schedule because the Node doesn't have enough resource available. The GKE autopilot cluster-autoscaler should update the nodes configuration, to start new nodes with enough resources, but it can take few minutes.
* Some agent are not ready (liveness failure): Could you provide the output of the command  `kubectl describe pod <pod-name>` for an agent pod that is never ready.

  The information that we are looking for is with "container"  is not ready, in your case it can be: `agent`, `trace-agent` or `process-agent`.

  When you know it can be also useful to have the output of `kubectl logs -p pod  <pod-name> -c <container-name>`

**Comment by stephaneetje** [comment]
Hello, thanks for your fast answer!
I could find the problem concerning the failed pods (i had a glitch in my apikey...)
Now  2 of 5 pods are 3/3 :
```
$  kubectl get pods
NAME                                     READY   STATUS    RESTARTS   AGE
datadog-8tvs7                            0/3     Pending   0          12m
datadog-cluster-agent-79b7444bcb-z5thw   1/1     Running   0          12m
datadog-gsk6f                            3/3     Running   0          12m
datadog-mx89v                            0/3     Pending   0          12m
datadog-qd8kd                            0/3     Pending   0          12m
datadog-tvf44                            3/3     Running   0          12m
```

Here is one of the 3 pods which aren't running
```
Events:
  Type     Reason             Age                   From                                   Message
  ----     ------             ----                  ----                                   -------
  Normal   NotTriggerScaleUp  2m26s (x98 over 12m)  cluster-autoscaler                     pod didn't trigger scale-up (it wouldn't fit if a new node is added): 5 node(s) didn't match Pod's node affinity
  Warning  FailedScheduling   49s (x10 over 12m)    gke.io/optimize-utilization-scheduler  0/5 nodes are available: 1 Insufficient cpu, 4 node(s) didn't match Pod's node affinity.
```

It has been 16mn now and nothing is changing. As i'm in autopilot mode, i can't manages the nodes. Is there something i should do ?
Here is the get nodes :
``` 
k get nodes
NAME                                            STATUS   ROLES    AGE     VERSION
gk3-qbel1-ciam-gke-default-pool-1ca643e7-1y66   Ready    <none>   4d4h    v1.20.8-gke.2100
gk3-qbel1-ciam-gke-default-pool-1ca643e7-tiyh   Ready    <none>   4d4h    v1.20.8-gke.2100
gk3-qbel1-ciam-gke-default-pool-bf83fb66-0ut5   Ready    <none>   4d4h    v1.20.8-gke.2100
gk3-qbel1-ciam-gke-default-pool-bf83fb66-6lyk   Ready    <none>   4d3h    v1.20.8-gke.2100
gk3-qbel1-ciam-gke-nap-9ldyq8fa-94efd17a-7mcf   Ready    <none>   3d11h   v1.20.8-gke.2100
```

**Comment by stephaneetje** [comment]
I finally decided to not use autopilot

**Comment by cloudgk** [comment]
> @stephaneetje I used this thread a lot as I was facing the same issues. Here's what helped me move forward.
> 
> [This](https://youtu.be/3EVt5lVfyPo?t=974) tweak with the PriorityClass.
> 
> Checking quotas and cluster logs. In our case all quotas were fine, but we had exhausted the internal IPs of the subnet we were running in the Autopilot cluster on. This was visible in the cluster logs (available in the Console as a separate tab) showing message `"messageId": "scale.up.error.ip.space.exhausted"`
> 
> These are all things on GCP's side and not Datadog, but since Datadog is one of the first things that go on the cluster, I figured it will be useful if I leave this info here.

That video was the lifesaver. Thanks man!!
