### ISSUE TITLE
Option for not mounting passwd or providing an empty dummy file

### ISSUE THREAD

**Issue by mologie** [DataDog/helm-charts#273]
**Describe what happened:**

I attempted to deploy Datadog Agent with helm to a Talos.dev cluster with default values.yaml, except I enabled the process agent. The Datadog daemonset attempted to mount /etc/passwd from the host, which does not exist on Talos. The daemonset would thus not start.

**Describe what you expected:**

The Datadog agent would deploy normally.

**Steps to reproduce the issue:**

1. Spawn a dummy talos.dev cluster
2. helm install --set datadog.processAgent.enabled=true ...
3. Observe that the daemonset pods fail to start (failed to create directory /etc/passwd)

Workaround: The daemon starts after patching the daemonset to remove the /etc/passwd volume.

**Additional environment details (Operating System, Cloud provider, etc):**

Talos 0.10

**Comment by mologie** [comment]
The workaround can be automated by patching the DaemonSet via helm and a post-renderer hook using yq:

datadog-passwd-fix.sh:
```
#!/bin/sh
exec yq e 'del(.. | select(has("name")) | select(.name == "passwd"))' -
```

```
helm install datadog-agent datadog/datadog --post-renderer="$PWD/datadog-passwd-fix.sh" ...
````

**Comment by clamoriniere** [comment]
hello @mologie 

Can we add instead `type: FileOrCreate` to the hostpath volume definition?

**Comment by mologie** [comment]
I do not believe so. Talos' root file system is readonly, thus creation of /etc/passwd on the host will fail. The options I see are either adding a flag indicating that /etc/passwd is unavailable (the agent works just fine without it anyway), or working with the folks from Talos Systems to have Talos provide a dummy passwd with just the root user. I believe that the flag would be the more portable solution.

**Comment by clamoriniere** [comment]
about the readonly file system, that's what I thought too

So I think adding an option in the `values.yaml` file to avoid mounting the `/etc/passwd` file is the best approach. Becasue the problem that I see with the `post-render` approach is it will not work for some users since it depends on the OS where the `helm` command runs.

Also, I see another issue for deploying the agent on Talos.dev: if you enable the `log` support, the agent will try to mount hostpath in read/write mode. This volume should be converted to a `LocalVolume` is Talos.dev support it.

**Comment by mologie** [comment]
The /var/log/pods path is a read-write xfs partition in Talos. The Datadog agent works correctly with it and maintains a read-only mount via its DaemonSet.

**Comment by clamoriniere** [comment]
Agree `/var/log/pods` and `var/log/containers` are mounter in `readonly` mode. 

But, the datadog log agent needs a file (simple json file) on the host to store pointer for each file it is tailing. this file is useful for the agent after a restart (daemonset update or agent process restart) to be able to restart tailing files where it stoped and so avoiding sending twice the same logs.

**Comment by mologie** [comment]
This feature works fine on Talos too -- all of `/var` is just a standard writable partition. I see that the agent's DaemonSet creates /var/lib/datadog-agent for that purpose and can confirm that log trailing info is persisted properly there.

**Comment by armenr** [comment]
^^ I'm running into the same issue with datadog + K3s. This thread, and the `datadog-passwd-fix.sh` post-render hack may just be the way to work around this.

Going to test and report back...but just wanted to share that even outside of Talos, this is a problem. I wonder if it should be raised with DataDog (GitHub issue), or through their support.

**Comment by myoung34** [comment]
I got this mostly working with talos by removing the system-process altogether (because it wont work with Talos for me) and patching out the passwd:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog

resources:
  - namespace.yaml
  - secrets.yaml #my sealed secret
patches:
  - path: patch.json
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: datadog
patchesStrategicMerge:
 - patch.yaml

helmCharts:
- name: datadog
  releaseName: datadog
  version: 3.1.3
  includeCRDs: true
  repo: https://helm.datadoghq.com
  valuesInline:
    datadog:
      apiKeyExistingSecret:  datadog
      logs:
        enabled: true
        containerCollectAll: true
      networkMonitoring:
        enabled: true
      serviceMonitoring:
        enabled: true
    clusterAgent:
      volumes:
        - hostPath:
            path: /run/containerd/containerd.sock
          name: containerdsocket
      volumeMounts:
        - name: containerdsocket
          mountPath: /var/run/containerd/containerd.sock
      securityAgent:
        compliance:
          enabled: true
        runtime:
          enabled: true
          syscallMonitor:
            enabled: false
    kube-state-metrics:
      nodeSelector:
        kubernetes.io/arch: amd64
    agents:
      podAnnotations:
        container.apparmor.security.beta.kubernetes.io/agent: unconfined
        container.apparmor.security.beta.kubernetes.io/process-agent: unconfined

```

patch.json 
These values always exist, this chart has no way to turn off the `system-probe` container

```
[
  {"op": "remove",
   "path": "/spec/template/metadata/annotations/container.seccomp.security.alpha.kubernetes.io~1system-probe",
   "value": "localhost/system-probe"},
  {"op": "remove",
   "path": "/spec/template/metadata/annotations/container.apparmor.security.beta.kubernetes.io~1system-probe",
   "value": "unconfined"}
]
```

patch.yaml
Same as above, cant turn off so delete

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog
spec:
  template:
    spec:
      volumes:
      - $patch: delete
        name: passwd
      containers:
      - name: process-agent
        volumeMounts:
        - $patch: delete
          mountPath: /etc/passwd
      - $patch: delete
        name: system-probe
```

**Comment by mologie** [comment]
For reference here is how I deployed Datadog agent under Talos 1.3. It needs two more workarounds:

* os-release-file needs to be removed in addition to removing the passwd mount described in this ticket.
* Node name detection does not work. Instead, it always uses the current container's hostname as node name and claims the node is down when the container is replaced. Setting DD_HOSTNAME to nodeName appears to work around the issue. This is inconsistent with Datadog's usual canonical machine naming where the cluster name is usually appended.

<hr/>

(Set your own API key, and adjust your Datadog agent features to match what you'd like to enable.)

```
$ cat datadog-hostmount-fix.sh
#!/bin/sh
exec yq e 'del(.. | select(has("name")) | select(.name == "passwd" or .name == "os-release-file"))' -
$ ddog_ignore_tags=(
  image:docker.io/calico/node
  image:gcr.io/datadoghq/agent
  image:gcr.io/datadoghq/cluster-agent
  kube_namespace:metallb-system
)
$ kubectl create ns datadog
$ kubectl -n datadog create secret generic datadog-secret --from-literal=api-key=API_KEY
$ cluster_name=foo
$ cluster_availability_zone=bar
$ cluster_env=baz
$ helm upgrade --install datadog-agent datadog/datadog \
  --post-renderer="$PWD/datadog-hostmount-fix.sh" \
  --namespace datadog \
  --set 'datadog.apiKeyExistingSecret=datadog-secret' \
  --set 'datadog.apm.portEnabled=true' \
  --set "datadog.clusterName=$cluster_name" \
  --set "datadog.containerExclude=${ddog_ignore_tags[*]}" \
  --set 'datadog.criSocketPath=/system/run/containerd/containerd.sock' \
  --set 'datadog.dogstatsd.useHostPort=true' \
  --set 'datadog.env[0].name=DD_HOSTNAME' \
  --set 'datadog.env[0].valueFrom.fieldRef.fieldPath=spec.nodeName' \
  --set 'datadog.env[1].name=DD_INVENTORIES_CONFIGURATION_ENABLED' \
  --set 'datadog.env[1].value=true' \
  --set 'datadog.logs.containerCollectAll=true' \
  --set 'datadog.logs.enabled=true' \
  --set 'datadog.processAgent.processCollection=true' \
  --set 'datadog.site=datadoghq.eu' \
  --set "datadog.tags={\"availability-zone:$cluster_availability_zone\",\"env:$cluster_env\"}" \
  --set 'clusterAgent.replicas=2' \
  --set 'clusterAgent.createPodDisruptionBudget=true'
```

**Comment by orellazri** [comment]
Hey all, thanks for all the useful info.
After setting up the values and creating a patch for removing the passwd and os-release-file mounts, the DaemonSet pods still fail with:

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/ce6d6748-20b6-45a0-91f3-38f4725359d7/volumes/kubernetes.io~empty-dir/auth-token" to rootfs at "/etc/datadog-agent/auth": mkdir /run/containerd/io.containerd.runtime.v2.task/k8s.io/trace-agent/rootfs/etc/datadog-agent/auth: read-only file system: unknown
```

Anyone here encountered this?

**Comment by bahuma20** [comment]
If you are using `datadog-operator` you can achive this patching with a custom kyverno policy that i wrote.

Maybe this helps someone:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: patch-datadog-agent
  annotations:
    policies.kyverno.io/title: Patch Datadog Agent
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: DaemonSet
    policies.kyverno.io/description: >-
      Removes /passwd and systemprobe mounts from datadog agent pods, so they can start correctly on readonly file system
spec:
  background: false
  rules:
    - name: remove-passwd
      match:
        any:
          - resources:
              kinds:
                - DaemonSet
              names:
                - datadog-agent
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                volumes:
                  - $patch: delete
                    name: passwd
                containers:
                  - name: process-agent
                    volumeMounts:
                      - $patch: delete
                        mountPath: /etc/passwd
                  - $patch: delete
                    name: system-probe
    - name: remove-system-probe
      match:
        any:
          - resources:
              kinds:
                - DaemonSet
              names:
                - datadog-agent
      mutate:
        patchesJson6902: |-
          - op: remove
            path: "/spec/template/metadata/annotations/container.seccomp.security.alpha.kubernetes.io~1system-probe"
            value: "localhost/system-probe"
          - op: remove
            path: "/spec/template/metadata/annotations/container.apparmor.security.beta.kubernetes.io~1system-probe"
            value: unconfined
```

**Comment by clamoriniere** [comment]
Hello Everyone,

We’ve added a new option in the datadog chart to support Kubernetes clusters running on Talos (talos.dev).

By adding the following configuration to your values.yaml file, the datadog chart installation should now work seamlessly on a Talos.dev cluster:

```yaml
datadog:
  # ...

providers:
  talos:
    enabled: true
```

Please let us know if this works for you. Any feedback is greatly appreciated!

**Comment by aureleoules** [comment]
Hello, can we also support running the Datadog Operator on Talos?
My process agent is also failing with this error log:
```
$ kubectl describe pod datadog-agent-4msms
...
Error: failed to generate container "381aa89ec528ffc3ac5df6c64aa5425ab143f3b6f19ac00ff868cbb17855e0e8" spec: failed to generate spec: failed to mkdir "/etc/passwd": mkdir /etc/passwd: read-only file system
```

**Comment by jfmatth** [comment]
> Hello Everyone,
> 
> We’ve added a new option in the datadog chart (version `3.83.0`) to support Kubernetes clusters running on Talos (talos.dev).
> 
> By adding the following configuration to your values.yaml file, the datadog chart installation should now work seamlessly on a Talos.dev cluster:
> 
> datadog:
>   # ...
> 
> providers:
>   talos:
>     enabled: true
> Please let us know if this works for you. Any feedback is greatly appreciated!
> 
> cc: [@faelis](https://github.com/faelis)

I tried installing the helm chart with the talos enabled, but now I get a failure of the hostname lookup

```
k logs datadog-agent-nqkbf
Defaulted container "agent" out of: agent, trace-agent, process-agent, init-volume (init), init-config (init)
2024-12-24 23:41:49 UTC | CORE | INFO | (pkg/util/log/log.go:841 in func1) | Starting to load the configuration
2024-12-24 23:41:49 UTC | CORE | WARN | (pkg/util/log/log.go:886 in func1) | Unknown environment variable: DD_GIT_REPOSITORY_URL
2024-12-24 23:41:49 UTC | CORE | WARN | (pkg/util/log/log.go:886 in func1) | Unknown environment variable: DD_GIT_COMMIT_SHA
2024-12-24 23:41:49 UTC | CORE | INFO | (pkg/util/log/log.go:841 in func1) | Loading proxy settings
2024-12-24 23:41:49 UTC | CORE | INFO | (pkg/util/log/log.go:841 in func1) | Starting to resolve secrets
2024-12-24 23:41:49 UTC | CORE | WARN | (pkg/util/log/log.go:886 in func1) | Agent configuration relax permissions constraint on the secret backend cmd, Group can read and exec
2024-12-24 23:41:49 UTC | CORE | INFO | (pkg/util/log/log.go:841 in func1) | Finished resolving secrets
2024-12-24 23:41:49 UTC | CORE | INFO | (pkg/util/log/log.go:846 in func1) | 4 Features detected from environment: kubernetes,kube_orchestratorexplorer,cri,containerd
2024-12-24 23:41:49 UTC | CORE | INFO | (pkg/runtime/runtime.go:28 in func1) | runtime: set GOMAXPROCS to: 4
2024-12-24 23:41:49 UTC | CORE | INFO | (pkg/process/metadata/workloadmeta/extractor.go:84 in NewWorkloadMetaExtractor) | Instantiating a new WorkloadMetaExtractor
2024-12-24 23:41:49 UTC | CORE | INFO | (comp/core/tagger/taggerimpl/tagger.go:171 in newTaggerClient) | TaggerClient is created, defaultTagger type:  *local.Tagger
2024-12-24 23:41:49 UTC | CORE | INFO | (comp/forwarder/defaultforwarder/default_forwarder.go:249 in NewDefaultForwarder) | Retry queue storage on disk is disabled
2024-12-24 23:41:52 UTC | CORE | INFO | (comp/forwarder/defaultforwarder/default_forwarder.go:249 in NewDefaultForwarder) | Retry queue storage on disk is disabled
2024-12-24 23:41:53 UTC | CORE | ERROR | (comp/aggregator/demultiplexer/demultiplexerimpl/demultiplexer.go:77 in newDemultiplexer) | Error while getting hostname, exiting: unable to reliably determine the host name. You can define one in the agent config file or in your hosts file
Error: Error while getting hostname, exiting: unable to reliably determine the host name. You can define one in the agent config file or in your hosts file
jfmatth@lg-John:~/development/home-charts/datadog$ helm ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
datadog-agent   default         1               2024-12-24 15:04:40.421613006 -0800 PST deployed        datadog-3.85.0  7
jfmatth@lg-John:~/development/home-charts/datadog$


```

**Comment by jfmatth** [comment]
OK, after reading the values.yaml file around Talos, I updated the pod security for the datadog namespace.

Now, I'm getting metrics back, but have a new error on node tags
```
2024-12-25 16:49:10 UTC | CORE | ERROR | (pkg/util/kubernetes/hostinfo/tags.go:76 in getNodeInfoTags) | Unable to auto discover node labels: temporary failure in clusterAgentClient, will retry later: try delay not elapsed yet
```

the data is at least coming back to DD, which makes life very easy :)

**Comment by chdeliens** [comment]
> Hello Everyone,
> 
> We’ve added a new option in the datadog chart (version `3.83.0`) to support Kubernetes clusters running on Talos (talos.dev).
> 
> By adding the following configuration to your values.yaml file, the datadog chart installation should now work seamlessly on a Talos.dev cluster:
> 
> datadog:
>   # ...
> 
> providers:
>   talos:
>     enabled: true
> Please let us know if this works for you. Any feedback is greatly appreciated!
> 
> cc: [@faelis](https://github.com/faelis)


Hi @clamoriniere,

I'm running the latest Datadog Helm chart "datadog-3.118.4" on a Talos 1.10.4 node (arm64) and Kubernetes 1.32.5.
I set the `providers.talos.enabled` flag to `true` in the chart's values and set the Datadog's Kubernetes namespace's PodSecurity to `Privileged`.

The Datadog Agent pod shows issues with the `system-probe` container: 

```
spec: failed to apply OCI options: failed to mkdir "/etc/apt": mkdir /etc/apt: read-only file system   
```

Do you (or anyone 😊) have a workaround for this? It's blocking the deployment of our new Talos cluster with Datadog.

Thanks!

**Comment by chdeliens** [comment]
I ended up opening a new ticket for this ;) 
https://github.com/DataDog/helm-charts/issues/1939

**Comment by NikitaCOEUR** [comment]
### With a deployment of a Datadog agent with Datadog Operator
Another workaround that allows the Datadog Operator to deploy the Datadog Agent on a Talos cluster is to disable some specific features:
```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog-operator
spec:
  features:
    liveProcessCollection:
      enabled: false
    processDiscovery:
      enabled: false
    cspm:
      enabled: false
    cws:
      enabled: false
    ...
```
By disabling these features, the `/etc/passwd` mount is no longer added to the trace-agent and agent containers in the agent pod. As a result, the Datadog Agent can start correctly and is able to collect logs, metrics, and other telemetry data.
