### ISSUE TITLE
DD_APM_FILTER_TAGS_REJECT environment variable not working

### ISSUE THREAD

**Issue by marload** [DataDog/helm-charts#830]
**Describe what happened:**
I would like to not collect status 429 and healthcheck traces by adding the following environment variables to datadog helm values.
However, this code doesn't seem to reject the collection.

**Describe what you expected:**
status 429 trace and healthcheck trace should not be collected.

**Steps to reproduce the issue:**
values.yaml
```
datadog:
  env:
    - name: DD_APM_FILTER_TAGS_REJECT
      value: "http.path_group:/health,http.path_group:/healthcheck,http.status_code:429"
```
and
```
agents:
  containers:
    traceAgent:
      env:
        - name: DD_APM_FILTER_TAGS_REJECT
          value: "http.path_group:/health,http.path_group:/healthcheck,http.status_code:429"
```

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes, Datadog Helm Chart 3.1.11

https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=datadogyaml

**Comment by iordachescuandrei** [comment]
This case was discussed on public slack channel. 
The fix was using: 
`datadog:
  env:
    - name: DD_APM_FILTER_TAGS_REJECT
      value: |
        ["http.status_code:429", "http.path_group:/healthcheck"]`

I would say this issue can be closed.

**Comment by clemenspeters** [comment]
We faced issues with multiple values for `DD_APM_FILTER_TAGS_REJECT` as well.
For now `DD_APM_IGNORE_RESOURCES` in our `values.yaml` for the datadog agent seems to work:
```
    - name: DD_APM_IGNORE_RESOURCES
      value:
        [
          'GET /actuator/health',
          'GET google.devtools.cloudtrace.v2.TraceService/BatchWriteSpans',
        ]
```

Would (still) be nice to know how to actually use `DD_APM_FILTER_TAGS_REJECT` with multiple values.

**Comment by crice88** [comment]
I'm running into the same issue. Using the env var attached to an ecs service task. One value works no problem, but when using a csv it seems like the last value is the only one taken into account. Had to use the `blocklist` attribute in the node tracer lib in order to manage the issue.

**Comment by REBELinBLUE** [comment]
Also having this issue, has anyone solved it? `DD_APM_IGNORE_RESOURCES` doesn't help, as we don't want to drop all instances, just specific ones, for example those where the user agent is kube-probe

**Comment by ivanmartos** [comment]
Still facing original issue on datadog helm chart version `3.33.7`

**Comment by ivanmartos** [comment]
I have a feeling this env variable does not work at all

I have this span in DataDog
![Screenshot 2023-08-18 at 19 40 21](https://github.com/DataDog/helm-charts/assets/5867879/6d73fe12-ea05-44db-b927-ffed68db7637)

I tried adding under `agents.traceAgent.env`

```
        - name: DD_APM_FILTER_TAGS_REJECT
          value: |
            ["http.host:o229562.ingest.sentry.io"]
```
also
```            
        - name: DD_APM_FILTER_TAGS_REJECT
          value: http.host:o229562.ingest.sentry.io
```
Same happens if I try to add it under `datadog.env`. I also tried setting value for env var for multiple tags. For example
```
        - name: DD_APM_FILTER_TAGS_REJECT
          value: http.host:uplink.api.apollographql.com,http.host:xray-service.default
```
or even with json format
```
        - name: DD_APM_FILTER_TAGS_REJECT
          value: |
            ["http.host:uplink.api.apollographql.com","http.host:xray-service.default"]
```          

and nothing works. I can still see these traces in datadog.
When I ssh into `trace-agent` kubernetes container, I can see that env variable is correctly passed. I guess it is just not respected.

**Comment by REBELinBLUE** [comment]
I think it does work, in my terraform I have the following

```locals {
  DD_APM_IGNORE_RESOURCES = [
    // Used by symfony applications for healthchecks
    "_monitor.run",
    "_monitor.groups",

    // Used by older symfony applications for healthchecks
    "liip_monitor_list_groups",

    // Used by nginx as the resource name for healthchecks
    "GET /monitor/health/run",
    "GET /monitor/health/groups",

    // Node JS healthchecks
    "GET /healthcheck"
  ]

  DD_APM_FILTER_TAGS_REJECT = [
    // Various user agents of automated requests to ignore
    "http.useragent:kube-probe/1.25+",  // FIXME: See if we can programmatically get this as it has to be a static 
    "http.useragent:Prometheus/2.44.0", // string but will change when kubernetes or prometheus are upgraded

    // We don't care about OPTIONS requests at all
    "http.method:OPTIONS"
  ]
}```

and then in my "helm_release" resource, using chart version 3.33.7 I have the following

```
  set {
    name  = "agents.containers.traceAgent.envDict.DD_APM_IGNORE_RESOURCES"
    value = join("\\,", local.DD_APM_IGNORE_RESOURCES) // @see https://github.com/hashicorp/terraform-provider-helm/issues/226#issuecomment-468278115
    type  = "string"
  }

  set {
    name = "agents.containers.traceAgent.envDict.DD_APM_FILTER_TAGS_REJECT"
    // The value is a literal string representing a JSON array, and because of the terraform
    // issue mentioned above we also need to escape the commas
    value = replace(tostring(jsonencode(local.DD_APM_FILTER_TAGS_REJECT)), ",", "\\,")
    type  = "string"
  }```

The OPTIONS resource no longer appears in traces

this results in the following env on the pod

```
        - name: DD_APM_FILTER_TAGS_REJECT
          value: '["http.useragent:kube-probe/1.25+","http.useragent:Prometheus/2.44.0","http.useragent:NodePing","http.method:OPTIONS"]'
        - name: DD_APM_IGNORE_RESOURCES
          value: _monitor.run,_monitor.groups,liip_monitor_list_groups,GET /monitor/health/run,GET /monitor/health/groups,GET /healthcheck
```

**Comment by ivanmartos** [comment]
I tried again and it seems that only filtering out by tag `http.host` nor `http.path_group` does not work. I was able to successfully filter by tags `http.useragent`under env var `DD_APM_FILTER_TAGS_REJECT`

**Comment by REBELinBLUE** [comment]
https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=datadogyaml

take a look under "On the backend, Datadog creates and adds the following span tags to spans after ingestion. These tags cannot be used to drop traces at the Datadog Agent level."

`http.path_group` and `network.destination.ip` are specifically listed

**Comment by ivanmartos** [comment]
Yes I checked, however `http.host` is also not listed

**Comment by marload** [comment]
It's late, but I've addressed this issue. 

**Correct example**
```
agents:
  containers:
    traceAgent:
      env:
        - name: DD_APM_FILTER_TAGS_REJECT
          value: |
            ["http.path_group:/healthcheck", "http.path_group:/health"]
```

**Wrong example**
```
agents:
  containers:
    traceAgent:
      env:
        - name: DD_APM_FILTER_TAGS_REJECT
          value: ["http.path_group:/healthcheck", "http.path_group:/health"]
```

**Comment by ajgajg1134** [comment]
Hey everyone, sorry it looks like the documentation here for the env var wasn't correct. I've opened a [PR](https://github.com/DataDog/documentation/pull/19637) to get it corrected. Valid values for these env vars are SPACE separated, or a valid json array.

**Comment by tomiszili** [comment]
Hello all,

Im still facing with this issue. I want to use it with ECS service, so i added this env var section of the datadog agent container definition. But with no luck i tried with string and json array with escaping `/` and `"`but neither of them seems working.
Could you please send me a working value for this env var?
The agent version is 7.44.1

**Comment by SouzaGuilherme** [comment]
Hi! I try all solutions presentation here... But dons't work for me. I used helm chart in version 3.25.5. 

Problem persist DD_APM_FILTER_TAGS_REJECT and DD_APM_IGNORE_RESOURCES

**Comment by toroi05** [comment]
> We faced issues with multiple values for `DD_APM_FILTER_TAGS_REJECT` as well. For now `DD_APM_IGNORE_RESOURCES` in our `values.yaml` for the datadog agent seems to work:
> 
> ```
>   env:
>       - name: DD_APM_IGNORE_RESOURCES
>         value: GET /actuator/health, GET google.devtools.cloudtrace.v2.TraceService/BatchWriteSpans
> ```
> 
> Would (still) be nice to know how to actually use `DD_APM_FILTER_TAGS_REJECT` with multiple values.

This is working

**Comment by brettcurtis** [comment]
Thanks for all the good tips, everyone! I was able to get this working using the Datadog Kubernetes operator and DatadogAgent kind with the Terraform kubernetes manifest resource:

spec.override.nodeAgent.containers

```hcl
trace-agent = {
   env = concat(local.trace_agent_env_vars, var.trace_agent_env_vars)
}
```

locals.tf

```hcl
  trace_agent_env_vars = [

    # Ignoring Unwanted Resources in APM
    # https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources

    {
      name  = "DD_APM_FILTER_TAGS_REGEX_REJECT"
      value = "http.useragent:kube-probe/\\d+\\.\\d+ http.url:https?:\\/\\/[^\\/]+\\/favicon\\.ico"
    }
  ]
```

Note to @REBELinBLUE: If you haven't noticed yet, there is a specific variable for `REGEX_REJECT` hidden in the docs for your kube-probe version. I saw your code comment, so I decided to mention it.

**Comment by REBELinBLUE** [comment]
@brettcurtis Nice, thanks, looks like it was added in agent 7.49 and it was at 7.46 when I implemented that, definitely will look at revisiting that.
